//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDesignerFromDatabse
{
    using System;
    using System.Collections.Generic;

    //POCO class or Entity class or Domain Class
    
    public partial class Emp
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Dept_Id { get; set; }
    }
}
